### ISSUE TITLE
solveset(sinh(x)) doesn't returns all solutions

### ISSUE THREAD

**Issue by aktech** [skirpichev/omg#16]
```python
In [6]: solveset(sinh(x))
Out[6]: {0}
```
solve is better in this case: (though it doesn't returns all solutions)

```python
In [7]: solve(sinh(x))
Out[7]: [0, I*pi]
```

**Comment by skirpichev** [comment]
Both are wrong.

But at least, `solveset` (actually, `solveset_complex`) should raise the NotImplementedError, as it does for `sin`.  The `solveset_real` does correct things for `sin` (a correct answer here) and `sinh` (exception raised).

Thank you for bugreport ;-)

**Comment by aktech** [comment]
> Both are wrong.

Yes, I mentioned that, even solve doesn't returns all solutions in this case.

**Comment by skirpichev** [comment]
> even solve doesn't returns all solutions in this case

This is rather a "feature" of the old `solve`.  It can't represent an infinite set of solutions.

Practically speaking, the current issue is with `solveset_complex`.

**Comment by aktech** [comment]
Yes, I agree that, I had been following Harsh's work.

**Comment by skirpichev** [comment]
Now there is no wrong answer anymore, clear the label.
